version: 1.0.{build}
image: Visual Studio 2019
configuration: Release
environment:
  CODECOV_TOKEN: e8ebb1fe-fbb0-4dd2-9d30-9986cb2d94f4

# Cache chocolatey packages and Nuget packages. Nuget package cache is invalidated
# on any change to a project file, the choco cache on any change to the config
# nuget file.
cache:
- source/SharpGL/packages -> **/*.csproj
- C:/ProgramData/chocolatey/bin -> ./source/SharpGL/config.ps1
- C:/ProgramData/chocolatey/lib -> ./source/SharpGL/config.ps1

# Before building, restore Nuget packages and install dependencies.
before_build:
- ps: |
    nuget restore source/SharpGL/SharpGL.sln
    ./source/SharpGL/config.ps1

# Use our own build script as it hides some unneeded warnings.
build_script:
- ps: |
    ./source/SharpGL/build.ps1
    ./source/SharpGL/pack.ps1

# After the build as completed, analyse coverage and upload.
on_success:
- ps: ./source/SharpGL/coverage.ps1

# All packages will be stored as artifacts, and pushed.
# We need to make sure we specify 'source', otherwise we will also gather
# legacy artifacts from 'extensions', which really needs to be moved into
# a totally separate repository.
artifacts:
  - path: './source/**/*.nupkg'

# Deploy to Nuget and GitHub if we have pushed a tag.
deploy:
- provider: NuGet
  api_key:
    secure: TWio+nDN8Ew7+OH7J3tLcEoM6DmxrIwfAr+2Ag8ROWJUEnXyoSAZ/I1GxBgB0qMd
  on:
    APPVEYOR_REPO_TAG: true
- provider: GitHub
  auth_token:
    secure: KTWUORrnJKPKLSf/3ROLY50T9UfgTMnKHf3OjBOv8tlY/DAxtlglRU3eM+j45fMt
  on:
    APPVEYOR_REPO_TAG: true

